### ISSUE TITLE
OS X build MØD successful make runtime Traceback error

### ISSUE THREAD

**Issue by eric-smith-ELSI** [jakobandersen/mod#12] opened 2021-05-19 11:42 UTC
This is an attempt to build on Darwin - 18.7.0 - x86_64
No complaints by cmake or make, build claims to complete successfully.
At runtime, mod fails with the following output:

MØD Wrapper --------------------------------------------------------
Prefix: /usr/local/bin/..
MedØlDatschgerl version 0.12.0.8
Plugins ------------------------------------------------------------
Global (/usr/local/bin/../share/mod/plugins):
 mod: /usr/local/lib
Input --------------------------------------------------------------
(see out/input)
Command ------------------------------------------------------------
 python3 out/input
Running VM ---------------------------------------------------------
Traceback (most recent call last):
  File "out/input", line 9, in <module>
    import mod
  File "/usr/local/lib/mod/__init__.py", line 14, in <module>
    from . import libpymod
ImportError: dlopen(/usr/local/lib/mod/libpymod.so, 10): Symbol not found: _PyCMethod_New
  Referenced from: /usr/local/opt/boost-python3/lib/libboost_python39-mt.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python3/lib/libboost_python39-mt.dylib

real	0m0.229s
user	0m0.064s
sys	0m0.069s
Program failed! Exit code: 1

What information can I provide to help diagnose this?  
I am running  python38 @3.8.10 from macports, in order to get py38-sphinx @4.0.1, which cmake finds.  But no changes in why python is active in my system affects the above behavior.  

I have used the dependencies you indicate on your install page from the steps 
git clone --recursive https://github.com/jakobandersen/mod.git
./bootstrap.sh
pip3 install -r requirements.txt
and then the brew bundle from homebrew.

Thank you,
Eric

**Comment by jakobandersen** [comment] 2021-05-21 11:12
Hmm, these linker errors are unfortunately quite icky. I looks like the MØD Python bindings were compiled against Python 3.9, so if you are then later executing with Python 3.8 that might explain it.
What version does it write when you run ``python3 --version``?

**Comment by eric-smith-ELSI** [comment] 2021-05-21 11:30
Thanks Jakob.  It's Python 3.8.10.  I am pretty sure it is using the version of boost that was part of your git archive for initial dependencies.  The version and location are different from anything I installed, and in different directories.  I don't know how that affects which python libraries are selected if more than one version is installed.

**Comment by jakobandersen** [comment] 2021-05-21 12:45
The problem is quite likely due to this version mismatch, though my knowledge of the different installation mechanisms on macOS is rather limited.
The dependencies in the repository are not mentioning a specific version, but just the components (see https://github.com/jakobandersen/mod/blob/develop/Brewfile), so I guess 3.9 is the default version in Brew (https://formulae.brew.sh/formula/boost-python3).
The ``mod`` script explicitly calls ``python3`` (I should make that configurable), so if you can somehow make a (temporary) alias in your shell that makes ``python3`` point to the one from Homebrew, that may fix it.

**Comment by eric-smith-ELSI** [comment] 2021-05-22 05:38
Thanks Jakob,

I get a successful execution of mod if the path to the homebrew python3 (for me /usr/local/bin) is at the head of the $PATH in the user's current environment at runtime.  If the python3 being called is the macports installaation, I exit with a segmentation fault at the time of launching the VM (output below).

This seems to be independent of the build of mod, which may have been fine all along.  I tried re-assigning the symlink for python3 with the default path, pointing at either the macports or homebrew installation (both version 3.9.5) before cmake and make, and the runtime behavior was no different either way (segfault until I changed the $PATH at the time of executing mod  to put /usr/local/bin first).

This is curious, because either installation of python39 seems to work fine from the command line.

Anyway, this allows me to work.  (The Docker version also works; thank you!)
Best, 
Eric 

MØD Wrapper --------------------------------------------------------
Prefix: /usr/local/bin/..
MedØlDatschgerl version 0.12.0.8
Plugins ------------------------------------------------------------
Global (/usr/local/bin/../share/mod/plugins):
 mod: /usr/local/lib
Input --------------------------------------------------------------
(see out/input)
Command ------------------------------------------------------------
 python3 out/input
Running VM ---------------------------------------------------------
/usr/local/bin/mod: line 270: 92390 Segmentation fault: 11  "$@"

real	0m0.060s
user	0m0.041s
sys	0m0.014s
Program failed! Exit code: 139

**Comment by jakobandersen** [comment] 2021-05-25 06:28
It's strange if they are both the same Python version, but I guess they may have been compiled differently. Though, it's good that switching interpreter at least can make it work. For the next version I have added the environment variable ``MOD_PYTHON`` (and ``MOD_IPYTHON``) which can be used to overwrite the default interpreter just for ``mod``.
Unfortunately I don't think there is a way to directly prevent this issue, so I'm closing it for now. Feel free to reopen should new information be relevant.

**Closed as completed by jakobandersen** 2021-05-25 06:28 UTC
